name: Build ROS Package

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  ros_build:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic-ros-base-focal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install catkin tools and deps
        run: |
          sudo apt update
          sudo apt install -y git python3-catkin-tools python3-pip
          sudo apt install -y \
            ros-noetic-catkin \
            ros-noetic-actionlib \
            ros-noetic-geometry-msgs \
            ros-noetic-move-base-msgs \
            ros-noetic-rospy \
            ros-noetic-smach \
            ros-noetic-std-msgs
          
      - name: Build workspace
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          cp -r . ~/catkin_ws/src/
          cd ~/catkin_ws
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
          catkin init
          catkin config --extend /opt/ros/noetic
          catkin build
